basePath: /api/v1
definitions:
  dto.Coordinate:
    properties:
      lat:
        type: number
      lon:
        type: number
    required:
    - lat
    - lon
    type: object
  dto.ListSightingResponse:
    properties:
      id:
        type: integer
      image:
        type: string
      lat:
        type: number
      lon:
        type: number
      seenAt:
        type: string
      tigerId:
        type: integer
      userId:
        type: integer
    required:
    - id
    - image
    - lat
    - lon
    - seenAt
    - tigerId
    type: object
  dto.ListTigerResponse:
    properties:
      coordinate:
        $ref: '#/definitions/dto.Coordinate'
      dob:
        type: string
      id:
        type: integer
      lastSeen:
        type: string
      name:
        type: string
    required:
    - coordinate
    - dob
    - id
    - lastSeen
    - name
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 5
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      access_token:
        type: string
    required:
    - access_token
    type: object
  dto.SignupRequest:
    properties:
      email:
        type: string
      password:
        minLength: 5
        type: string
      userName:
        type: string
    required:
    - email
    - password
    - userName
    type: object
  dto.TigerCreateRequest:
    properties:
      coordinate:
        $ref: '#/definitions/dto.Coordinate'
      dob:
        type: string
      lastSeen:
        type: string
      name:
        type: string
    required:
    - coordinate
    - dob
    - lastSeen
    - name
    type: object
  interceptor.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:3000
info:
  contact: {}
  description: Tiger service API for tiger management and recording system
  title: Tiger service API
  version: "1.0"
paths:
  /sight:
    get:
      consumes:
      - application/json
      description: |-
        Sorted by the last time the tigers were seen.
        Supports pagination with page number and limit(number of records to fetch).
        Page and Limit must be valid integer. Default values: page - 1, limit - 5
      parameters:
      - description: Page number to be fetched
        in: query
        minimum: 1
        name: page
        type: integer
      - description: Number of records to be fetched
        in: query
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ListSightingResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/interceptor.Response'
      summary: List All Sighting of Tigers
      tags:
      - sighting
    post:
      consumes:
      - multipart/form-data
      description: |-
        Records last sighting of a tiger
        New sighting notifies all the user who reported a sighting for the same tiger in past.
        Will respond with conflict(409) status, If the previous sighting of the same tiger was within the 5 KM.
        NOTE: Access Token needed in Authorization header
      parameters:
      - in: formData
        name: lat
        required: true
        type: number
      - in: formData
        name: lon
        required: true
        type: number
      - in: formData
        name: seenAt
        required: true
        type: string
      - in: formData
        name: tigerId
        required: true
        type: integer
      - description: Tiger Image file
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/interceptor.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/interceptor.Response'
      security:
      - ApiKeyAuth: []
      summary: Create a new sighting of a tiger
      tags:
      - sighting
  /tiger:
    get:
      consumes:
      - application/json
      description: |-
        Sorted by the last time the tigers were seen.
        Supports pagination with page number and limit(number of records to fetch).
        Page and Limit must be valid integer. Default values: page - 1, limit - 5
      parameters:
      - description: Page number to be fetched
        in: query
        minimum: 1
        name: page
        type: integer
      - description: Number of records to be fetched
        in: query
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ListTigerResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/interceptor.Response'
      summary: List All Tigers
      tags:
      - tiger
    post:
      consumes:
      - application/json
      description: |-
        Creates a new tiger, Tiger name must be unique.
        D.O.B must be a string in format of "yyyy-mm-dd", ex: "2020-07-17".
        Last Seen must be a string representing UTC Date-Time in ISO 8601 format, ex: "2023-02-12T14:58:46Z".
        Lat and Lon must valid decimal values, ex: 35.083742442502925, 78.52220233592793
        NOTE: Access Token needed in Authorization header
      parameters:
      - description: Tiger Details
        in: body
        name: tiger
        required: true
        schema:
          $ref: '#/definitions/dto.TigerCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/interceptor.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/interceptor.Response'
      security:
      - ApiKeyAuth: []
      summary: Create Tiger
      tags:
      - tiger
  /user:
    post:
      consumes:
      - application/json
      description: |-
        Creates a new user
        Password Must be 5 character or more
      parameters:
      - description: User Details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/interceptor.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/interceptor.Response'
      summary: User Signup
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: |-
        Log the user in by returning the API access_token (JWT)
        Use the access_token in further API calls inside Authorization Header
      parameters:
      - description: User Creds
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/interceptor.Response'
      summary: User Login
      tags:
      - user
  /user/refresh:
    get:
      consumes:
      - application/json
      description: |-
        Refreshes the user access token by providing a new/fresh access token.
        Token refresh only happens within 1 hour of current token expiry
        NOTE: Access Token needed in Authorization header
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/interceptor.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/interceptor.Response'
      security:
      - ApiKeyAuth: []
      summary: User Token Refresh
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
